---
title: Analysis 1
description:
toc: true
featuredVideo: 
featuredImage: https://learn.g2.com/hubfs/Imported%20sitepage%20images/1ZB5giUShe0gw9a6L69qAgsd7wKTQ60ZRoJC5Xq3BIXS517sL6i6mnkAN9khqnaIGzE6FASAusRr7w=w1439-h786.png
draft: false
---


<div id="TOC">

</div>

<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Most of our teammates are international students from China and Korea. We found an article that the number of international students in the US unprecedentedly still increased during 2019to 2021. Widespread travel restrictions do not appear to have had a large impact on freshmen applying to U.S. universities from outside the U.S. We wanted to see what influences international students to choose certain institutions in the United States.</p>
<p>One of our teammates, Yawei suggested that the top three considerations were: safety, ranking of the university in my field, and the “dynamics” of the campus. The percentage of the international student body would fall under the third category. However, while there has been quite convenient data on the first two categories, the judgment of the third was more based on gut or anecdotes. The rankings on US News, for example, are a weighted composite score of many aspects, but we were not sure whether the international student body is one of the criteria (probably not, but I believe there is correlation there). Therefore, we considered that we could explore more about this potential correlation (x=% of international students, y=rankings) while trying to add in other interesting and relevant information, such as the nationalities of international students, crime rate of the city, etc</p>
<p>The “main” research question is to explore the relationship between percentage of international student population (x-axis) and the ranking of US universities (y-axis). We can then add more interesting complexities/layers to the basic graph through “group_by”, “color”, “fill”, “facet” and different “geoms_plots” using variables such as nationalities, number of (top xx) universities in the city, crime rates of the city, location of the university (on a US map), and ranking type (e.g., undergraduate, graduate cs, graduate education, graduate business, graduate law).</p>
<p>We also wanted to answer the questions below:
How has the number of international students in the US changed over time? (x= school years, y= international students’ population)
New enrollment percentage of international students (x= school years, y= international students’ population % change)
How do new enrollment trends vary by academic level?
Breakdown of international students by the US region they live (2021 vs 2016)</p>
</div>
<div id="breadth-and-depth-of-da" class="section level2">
<h2>Breadth and Depth of DA</h2>
<p>Our group’s target variables are the international student population (ISPo) and proportion (ISPr) in US colleges, and we aim to identify the potential factors that correlate to and predict ISPo and ISPr.</p>
</div>
<div id="early-data-analysis" class="section level2">
<h2>Early Data Analysis</h2>
<p>In our earlier data analysis (Blog Post 4), we examined the relationship between the dependent variable ISPr and the independent variable, an additive indicator reflecting the number of “Alumni of an institution winning Nobel Prizes and Fields Medals” and “Papers indexed in Science Citation Index-Expanded and Social Science Citation Index”. We did this by making predictions with 7 regression models (logistic, quasipolynomial, Gaussian, Poisson, Inverse Gaussian, Gamma) after shuffling and splitting the data with a 70-30 ratio for the train and test sets. By evaluating the AIC and fisher score, we selected the inverse gaussian glm as the best fit of all 7 models. Below we display our linear regression, logistic regression, and inverse gaussian regression.<br />
<br>
One main limitation is that we naively selected one feature, a linear combination of variables on notable alumni with high research and publications, for modelling. Below in the Feature Extraction section, we remedy this problem by experimenting on all predictor variables to select the most promising features to be learned.<br />
<br>
Another main limitation is that we have missing and incorrect data over 300 observations. In particular, we had issues with variables city, state, city_population, city_population_density. We resolved this by imputing the missing values and manually correcting by using US Census and universities’ published data as discussed in our Data Page.</p>
</div>
<div id="feature-extraction" class="section level2">
<h2>Feature Extraction</h2>
<p>We extract the most significant independent variables to improve model performance using two methods:
correlation matrix for continuous predictors and logistic regression for categorical predictors.<br />
<br>
Since we are solving a regression problem, our output is a continuous variable. After data cleaning, we have 35 independent variables concerning every observed college. They are split into 20 continuous variables and 15 categorical variables.</p>
<div id="continuous-predictors" class="section level3">
<h3>Continuous Predictors</h3>
<p>To explore continuous variables’ correlations with the target variables, we have used a correlation matrix.
<img src="/analysis_files/figure-html/unnamed-chunk-1-1.png" width="672" />
We identified pairs of variables with high positive or negative correlations and selected numerical features that have an absolute value of correlation coefficient greater than 0.4 with respect to ISPo and ISPr.</p>
<div id="for-ispo-the-relevant-numerical-features-are" class="section level4">
<h4>For ISPo, the relevant numerical features are:</h4>
<ol style="list-style-type: decimal">
<li>international_students_opendoors,<br />
</li>
<li>enrollment_top120enrollment,<br />
</li>
<li>city_population,<br />
</li>
<li>international_students_qs,<br />
</li>
<li>international_students_natlib,<br />
</li>
<li>city_population_density</li>
</ol>
</div>
<div id="for-ispr-the-relevant-numerical-features-are" class="section level4">
<h4>For ISPr, the relevant numerical features are:</h4>
<ol style="list-style-type: decimal">
<li>city_population_density<br />
</li>
<li>faculty_count_qs</li>
</ol>
</div>
</div>
<div id="categorical-predictors" class="section level3">
<h3>Categorical Predictors</h3>
<p><b>Note</b>: Before using logistic regression, we omit variable “university” because it is unique for all observations.<br />
<br>
We build logistic regression models with single categorical variable predictors and pairs of categorical variable predictors. For readability, we omit the models with paired predictors. However, we document all performances in the R code block. We select variables from models using the Akaike information criterion (AIC) metric. Below, we provide the summary of the logistic regression model with response variable international student population and independent variable research output.</p>
<pre><code>## 
## Call:
## glm(formula = as.factor(international_students_max) ~ research_output_qs, 
##     family = binomial(), data = prev_data, na.action = na.omit)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.1656   0.1157   0.1157   0.1157   0.1157  
## 
## Coefficients:
##                             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)                    20.57    3412.21   0.006    0.995
## research_output_qsVery High   -15.56    3412.21  -0.005    0.996
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 12.347  on 176  degrees of freedom
## Residual deviance: 12.015  on 175  degrees of freedom
##   (264 observations deleted due to missingness)
## AIC: 16.015
## 
## Number of Fisher Scoring iterations: 19</code></pre>
<div id="for-ispr-the-relevant-categorical-features-are" class="section level4">
<h4>For ISPr, the relevant categorical features are:</h4>
<ol style="list-style-type: decimal">
<li>research_output_qs<br />
</li>
<li>size_qs<br />
</li>
<li>locale_carnegie<br />
</li>
<li>enrprofile2021_carnegie<br />
</li>
<li>type2_carnegie<br />
</li>
<li>type4_carnegie</li>
<li>world_rank_cat_arwu<br />
</li>
<li>selectivity<br />
</li>
<li>state</li>
</ol>
</div>
<div id="for-ispo-the-relevant-categorical-features-are" class="section level4">
<h4>For ISPo, the relevant categorical features are:</h4>
<ol style="list-style-type: decimal">
<li>research_output_qs<br />
</li>
<li>size_qs<br />
</li>
<li>type3_natlib<br />
</li>
<li>type4_carnegie<br />
</li>
<li>state<br />
</li>
<li>selectivity<br />
</li>
<li>world_rank_cat_arwu</li>
</ol>
</div>
</div>
<div id="finalized-features" class="section level3">
<h3>Finalized Features</h3>
<p>Since our data is sparse, if we select certain variables for our predictors, then many college observations are dropped. Thereby, for predicting both international student population and proportion, out of our initial 35 dependent variables, we select the features:<br />
1. city_population<br />
2. city_population_density<br />
3. selectivity<br />
4. size_qs<br />
5. research_output_qs</p>
<div id="the-following-modeling-section-exclusively-addresses-our-data-analysis." class="section level4">
<h4>The following modeling section exclusively addresses our data analysis.</h4>
</div>
</div>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<div id="initial-modeling" class="section level3">
<h3>Initial Modeling</h3>
<p>For our first iteration of modeling, we use the dataset with 35 independent variables and only consider models with numerically extracted features: faculty_count_qs, city_population, city_population_density.
To obtain our train and test datasets, we have performed an <b>70-30 random shuffle-split</b>. We have 53 examples in the train set and 23 examples in test set. Then, we model ISPo with linear and logistic regression.</p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-3-1.png" width="672" /><img src="/analysis_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre><code>## [1] &quot;Mean Absolute Error of Linear Regression for ISPr:&quot;</code></pre>
<pre><code>## [1] 0.03342281</code></pre>
<pre><code>## [1] &quot;Mean Absolute Error of Logistic Regression for ISPr:&quot;</code></pre>
<pre><code>## [1] 0.03372792</code></pre>
<p>While linear regression has a mean absolute error of <em>0.03342281</em> and logistic regression has a mean absolute error of <em>0.03372792</em> suggests the models have ‘low’ error, the modelling is not robust since the train and test set are small, only contains 53 and 23 observations, respectively. We are interested in experimenting with more test data and using a combination of continuous and categorical predictors for the final modeling.</p>
</div>
<div id="finalized-modeling" class="section level3">
<h3>Finalized Modeling</h3>
<p>To improve upon our last iteration of modeling, we have imputed city population and density data for all university observations, which enables more available training and test data. We also have selected highly-correlated predictors for this regression problem to improve model performance.<br />
<br>
To obtain our train and test datasets, we have performed an <b>80-20 random shuffle-split</b>. We have 352 examples in the train set and 89 examples in test set.<br />
<br>
Then using our pruned features, we model ISPo and ISPr with <b>logistic regression, stepwise linear regression with forward and backward selection, and inverse gaussian regression</b>.<br />
<br>
Below, we present the logistic regression and inverse gaussian regression models and model evaluations.</p>
<pre><code>## [1] &quot;Mean Absolute Error of Logistic Regression for ISPr:&quot;
## [1] 0.05272577
## [1] &quot;Mean Absolute Error of Logistic Regression for ISPo:&quot;
## [1] 4755.231
## [1] &quot;Mean Absolute Error of Inverse Gaussian Regression for ISPr:&quot;
## [1] 0.06059221
## [1] &quot;Mean Absolute Error of Inverse Gaussian Regression for ISPo:&quot;
## [1] 1898.074</code></pre>
<p>For evaluating performance on these two generalized linear models, we compute for mean absolute error (MAE) on the new test set with 89 examples.<br />
<br>
For international student population, the inverse Gaussian regression has lower MAE and performs better than the logistic regression. Conversely, for international student proportion, the logistic regression has lower MAE and performs better.</p>
<div id="stepwise-linear-regression-models" class="section level4">
<h4>Stepwise linear regression models:</h4>
<pre><code>## 
## Call:
## lm(formula = international_students_natlib ~ city_population + 
##     city_population_density + selectivity + size_qs + research_output_qs, 
##     data = train)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.081879 -0.012494 -0.002227  0.018781  0.094264 
## 
## Coefficients:
##                                      Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)                         1.511e-02  3.140e-02   0.481   0.6334  
## city_population                     7.923e-09  4.820e-09   1.644   0.1095  
## city_population_density             1.906e-06  1.543e-06   1.235   0.2253  
## selectivityhighly competitive plus  4.676e-02  2.510e-02   1.863   0.0711 .
## selectivitymost competitive         1.156e-02  2.029e-02   0.570   0.5725  
## selectivityvery competitive plus    9.396e-03  2.894e-02   0.325   0.7474  
## size_qsM                            6.111e-04  1.394e-02   0.044   0.9653  
## size_qsS                           -2.111e-02  2.577e-02  -0.819   0.4183  
## size_qsXL                          -4.456e-02  2.192e-02  -2.033   0.0499 *
## research_output_qsVery High         6.852e-02  2.512e-02   2.727   0.0100 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.03753 on 34 degrees of freedom
##   (308 observations deleted due to missingness)
## Multiple R-squared:  0.5279, Adjusted R-squared:  0.403 
## F-statistic: 4.225 on 9 and 34 DF,  p-value: 0.000983</code></pre>
<pre><code>## 
## Call:
## lm(formula = international_students_natlib ~ city_population + 
##     city_population_density + selectivity + size_qs + research_output_qs, 
##     data = train)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.081879 -0.012494 -0.002227  0.018781  0.094264 
## 
## Coefficients:
##                                      Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)                         1.511e-02  3.140e-02   0.481   0.6334  
## city_population                     7.923e-09  4.820e-09   1.644   0.1095  
## city_population_density             1.906e-06  1.543e-06   1.235   0.2253  
## selectivityhighly competitive plus  4.676e-02  2.510e-02   1.863   0.0711 .
## selectivitymost competitive         1.156e-02  2.029e-02   0.570   0.5725  
## selectivityvery competitive plus    9.396e-03  2.894e-02   0.325   0.7474  
## size_qsM                            6.111e-04  1.394e-02   0.044   0.9653  
## size_qsS                           -2.111e-02  2.577e-02  -0.819   0.4183  
## size_qsXL                          -4.456e-02  2.192e-02  -2.033   0.0499 *
## research_output_qsVery High         6.852e-02  2.512e-02   2.727   0.0100 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.03753 on 34 degrees of freedom
##   (308 observations deleted due to missingness)
## Multiple R-squared:  0.5279, Adjusted R-squared:  0.403 
## F-statistic: 4.225 on 9 and 34 DF,  p-value: 0.000983</code></pre>
<pre><code>## 
## Call:
## lm(formula = international_students_max ~ city_population_density + 
##     size_qs + research_output_qs, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4958.8 -1368.3  -166.5   865.5  9032.6 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                  3.963e+02  5.842e+02   0.678  0.49871    
## city_population_density      1.345e-01  2.909e-02   4.625 8.63e-06 ***
## size_qsM                    -1.539e+03  5.110e+02  -3.013  0.00309 ** 
## size_qsS                    -2.842e+03  1.093e+03  -2.600  0.01037 *  
## size_qsXL                    2.544e+03  4.874e+02   5.220 6.54e-07 ***
## research_output_qsVery High  1.878e+03  5.628e+02   3.337  0.00109 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2350 on 136 degrees of freedom
##   (210 observations deleted due to missingness)
## Multiple R-squared:  0.3907, Adjusted R-squared:  0.3683 
## F-statistic: 17.44 on 5 and 136 DF,  p-value: 2.557e-13</code></pre>
<pre><code>## 
## Call:
## lm(formula = international_students_max ~ city_population_density + 
##     size_qs + research_output_qs, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4958.8 -1368.3  -166.5   865.5  9032.6 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                  3.963e+02  5.842e+02   0.678  0.49871    
## city_population_density      1.345e-01  2.909e-02   4.625 8.63e-06 ***
## size_qsM                    -1.539e+03  5.110e+02  -3.013  0.00309 ** 
## size_qsS                    -2.842e+03  1.093e+03  -2.600  0.01037 *  
## size_qsXL                    2.544e+03  4.874e+02   5.220 6.54e-07 ***
## research_output_qsVery High  1.878e+03  5.628e+02   3.337  0.00109 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2350 on 136 degrees of freedom
##   (210 observations deleted due to missingness)
## Multiple R-squared:  0.3907, Adjusted R-squared:  0.3683 
## F-statistic: 17.44 on 5 and 136 DF,  p-value: 2.557e-13</code></pre>
<p>For evaluating stepwise linear regression, we are interested in finding models with the high adjusted R2 Score, low Bayesian Information Criterion, and low Mallow’s Cp.<br />
<br>
Notice that for ISPr, the best models from forward and backward are identical and the best predictors are city_population,city_population_density,selectivity,size_qs, and research_output_qs.<br />
<br>
Similarly, for ISPo, the best models from forward and backward are identical and the predictors are city_population_density, size_qs, and research_output_qs.<br />
<br>
We also see that the p-value scores are low for all models, which implies the predictors are statistically significant and are good indicators of prediction. Thus, we reject the null hypothesis and claim that we have identified good indicators of prediction of international student proportion and population.</p>
</div>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Our project concerns international student population and proportion of US colleges from 441 observations. Our analysis suggests that the city population, city population density, college selectivity, campus size, and faculty research output are good indicators for predicting international student population and international student proportion.</p>
</div>
<div id="flaws-and-limitations" class="section level1">
<h1>Flaws and limitations</h1>
<div id="initial-limitation-1-resolved." class="section level3">
<h3>Initial Limitation 1 (Resolved).</h3>
<p>One of the main limitations is that for our models we don’t introduce any categorical variables. We address this in the Feature Extraction section. Alternatively, we are interested in leveraging the regsubsets subroutine in the leaps library to compare modeling with different variables, which provides performance criteria such as Adjusted R2 score, Bayesian Information Criterion, Mallow’s Cp.</p>
</div>
<div id="solution" class="section level3">
<h3>Solution:</h3>
<p>We have done feature extraction using correlation matrix and logistic regression. We have also used regsubsets and the above metrics to find the most promising categorical and continuous predictors.
<br></p>
</div>
<div id="initial-limitation-2-resolved." class="section level3">
<h3>Initial Limitation 2 (Resolved).</h3>
<p>On the other hand, due to the sparsity of the data, if we include certain predictors, the overall data for training and testing may shrink to 10 observations, which leads to not unreliable modeling and predictions.</p>
</div>
<div id="solution-1" class="section level3">
<h3>Solution:</h3>
<p>We have imputed and corrected values for variables such as city, state, city_population, and city_population_density. In doing so, we are now able to work with up to at most 441 observations depending on selected predictors and also .
<br></p>
</div>
<div id="current-limitations-1-for-future-work" class="section level3">
<h3>Current Limitations 1 (For Future Work)</h3>
<p>While we have successfully revised the data using sources such as the US Census Bureau and the Univeristy page, we also have took it from sources such as <a href ="https://worldpopulationreview.com/"> World Population Review</a> and <a href ="http://www.city-data.com/"> City Data</a>. We are uncertain how reliable these sources are.</p>
</div>
<div id="proposed-solution" class="section level3">
<h3>Proposed Solution:</h3>
<p>To workaround this, the investigator could webscrape from more reputable sources and limit the number of dataset merges to lessen the missing values.</p>
</div>
<div id="current-limitations-2-for-future-work" class="section level3">
<h3>Current Limitations 2 (For Future Work)</h3>
<p>Again due to data sparsity, we still were only able to explore a few simple features. All of the predictors that we used were not “feature engineered”.</p>
</div>
<div id="proposed-solution-1" class="section level3">
<h3>Proposed Solution:</h3>
<p>For the next investigation, data on longitude and latitude of the universities could be explored to see whether distance (Euclidean, Manhattan, Harvesine, Cosine) to any international hubs or attractions. In general, the investigator could see try to see if there are any more non-linear relations between ISPr/ISPo and some combination or transformation of independent variables. The investigator would also need to apply some regularization penalties if there is overfitting from the feature engineering.</p>
<hr />
</div>
<div id="rubric-on-this-page" class="section level2">
<h2>Rubric: On this page</h2>
<p>you will</p>
<ul>
<li>Introduce what motivates your Data Analysis (DA)
<ul>
<li>Which variables and relationships are you most interested in?</li>
<li>What questions are you interested in answering?</li>
</ul></li>
<li>Breadth of the DA
<ul>
<li>Make sure that you ask enough initial questions to explore the different variables in your data.</li>
<li>i.e. Do you explore more than just one or two variables? Do you explore a few different relationships or many?</li>
</ul></li>
<li>Depth of the DA
<ul>
<li>When you answer one question, usually more questions arise as well.</li>
<li>The depth of the DA is about coming up with and exploring the answers to these questions, often iterating the process a few times.</li>
</ul></li>
<li>Modeling and Inference
<ul>
<li>You should also include some kind of formal statistical model and/or inference. This could be a linear regression, logistic regression, hypothesis testing etc.</li>
<li>Explain the techniques you used for validating your results.</li>
<li>Describe the results of your modelling and make sure to give a sense of the uncertainty in your estimates and conclusions.</li>
</ul></li>
<li>Explain the flaws and limitations of your analysis
<ul>
<li>Are there some assumptions that you needed to make that might not hold? Is there other data that would help to answer your questions? …</li>
</ul></li>
<li>Clarity Figures
<ul>
<li>Are your figures/tables/results easy to read, informative, without problems like overplotting, hard-to-read labels, etc?</li>
<li>Each figure should provide a key insight. Too many figures or other data summaries can detract from this.</li>
</ul></li>
<li>Clarity of Explanations
<ul>
<li>Do you introduce why you are doing each analysis?</li>
<li>How well do you explain each figure/result?</li>
<li>Do you provide interpretations that suggest further analysis or explanations for observed phenomenon?</li>
</ul></li>
<li>Organization and cleanliness.
<ul>
<li>Make sure to remove excessive warnings, use clean easy-to-read code, organize with sections or multiple pages, use bullets, etc.</li>
</ul></li>
</ul>
<p><strong>NOTE</strong>: Your Data Analysis can be broken up into multiple pages if that helps with your organization.</p>
</div>
</div>
