---
title: Interactive Ideas
author: ''
date: '2022-11-18'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-18T09:03:07-05:00'
featuredVideo: ~
featuredImage: ~
---

In this post, we first reported the 10 potential ideas for interactive that our team brainstormed. Then, we discussed one "full" picture on interactive which combined a few individual ideas together. 

## Idea 1

### Global:
A US map that shows the average population of the international students of each state (large circle: large population; small circle: small population)

### Interactive:
Input will be "select box" of the selectivity category of  each university; output will be a table (function: tableOutput) displaying key data points about the universities which meet the selected selectivity condition, in ascending order of the world university rank. 


## Idea 2

### Global:
A US map that shows a pin (or point) of all US universities.

### Interactive:
Input will be "Check box group" of key features (data points) of universities such as tuition and research output; output will be a table (function: tableOutput) displaying all data points about the universities which meet the selected selectivity condition, in ascending order of the world university rank. 


## Idea 3

### Global:
A US map that displays average world rank scores of universities in each state in our dataset (lighter shade indicates lower ranking scores) to demonstrate the quality of universities in US states.

### Interactive:
Input will be mouse click, which means people can click on the state they want to see (or they can also just check the state in "check box"); The first output will be a table displaying universities’ information in that state including university world rank and related scores, selectivity, etc. Then, there is another input after selecting “state” which will be the “university name” (text input). The output will be (1) a state's map showing the location of the university (city) and (2) an update of the table from the first output (from showing multiple universities to showing only the one university selected).

Example Source: https://rstudio.github.io/crosstalk/


## Idea 4

### Global:
A US map that displays average out-of-state tuition fee in each state categorized by public and private included by our dataset.

### Interactive:
Input will be the range of tuition fee like per year (slider range); output will have two parts. The first output will be a table displaying the tuition fee of the university which meets the range. Other information including international student population and student-faculty ratio will also be displayed. For the second output, there will be two plot-line graphs (plotsoutput, fit a model), the first one is the relationship between tuition fees and the number of international students in the tuition range chosen. The second is the relationship between tuition and faculty-student ratio in the tuition range chosen. In this way, people can see the relationship between tuition and these two variables. According to our previous research, tuition fees and teacher-student ratio are directly proportional to the number of international students.


## Idea 5

### Global:
A geographic heat map with relevant universities’ information (i.e. name, ranking publication, student faculty ratio, city, international student population, tuition).

### Interactive:
Input will be mouse based. Zooms into colleges for state(s), or US regions (the Northeast, Southwest, West) through mouse hovering. Output will be a display of relevant infomation in the heatmaps if mouse hovers on top/clicks the university.

Resources:

https://shiny.rstudio.com/gallery/plot-interaction-zoom.html

https://search.r-project.org/CRAN/refmans/shinyjs/html/onevent.html


## Idea 6

### Global:
Geographic heat map or general data.

### Interactive:
Input will be select a subset of data from tick boxes for categorical variables  (size, location type, public/private) and query a lower or upper bound for numerical variables (international student population, tuition, ranking publication). For example, based on international student percentage or top 100 rankings of the selected region. Output will be heatmaps with points of  universities.


Resources:

Tickbox: https://shiny.rstudio.com/reference/shiny/latest/checkboxInput.html 

Numeric Input: https://shiny.rstudio.com/reference/shiny/1.6.0/numericInput.html 


## Idea 7

### Global:
A US map that displays the number of universities included by our dataset (the lighter the shade, the fewer universities our dataset contains for that state).

### Interactive:
Input will be “slider range” of the number of international students; output will be a table (function: tableOutput) displaying several important data points (such as private/public, city, state, city/suburb/town, out-of-state tuition, student-faculty ratio, etc.) of the universities which meet the condition set in the slider.


## Idea 8

### Global:
A US map that displays the number of universities included by our dataset (the lighter the shade, the fewer universities our dataset contains for that state).

### Interactive:
Input will be “select box” of the world ranking of the universities; output will have two parts. The first part is a bar plot (function: plotOutput) of the number of international students at the universities which meet the ranking condition. The second part is an interactive table (function: dataTableOutput) displaying several important data points (such as private/public, city, state, city/suburb/town, out-of-state tuition, student-faculty ratio, etc.) of the universities which meet the condition set in the slider.


## Idea 9

### Global:
A US geographical map with 50 states that shows every universities we have for each state, the larger the international student population, the deeper the color of the states. 

### Interactive:
Input will be mouse based; Output will be a list of the universities when we click the specific state from the map. Then, we can also click the universities from the list. In this case, the output will be an interactive table. The table will display the rank, international student percentage and some data variables we consider significant (based on analysis).


## Idea 10

### Global:
A polar graph that displays the rank of current universities we have in our dataset. Each university will be a data point of the polar graph. 

### Interactive:
Input will be mouse based. Output will be a table displaying the international student percentage, state, and the important datapoints of each university when we click the data point of the polar graph. We also use the Zoom in function that zoom in the data point of specific US universities rank area. 


Zoom in Feature: https://github.com/rstudio/shiny-examples/blob/main/105-plot-interaction-zoom/app.R


## Way 1 of combining ideas (idea 1, 4, 5, 8, & 9)

### Global:
A US map that displays the number of universities included by our dataset (the lighter the shade, the fewer universities our dataset contains for that state) and the average population of the international students of each state (large circle: large population; small circle: small population).

### Interactive:
#### First level: 
Input will be mouse based. Zooms into colleges for state(s). Output will be an interactive table (function: dataTableOutput) displaying several important data points (such as private/public, city, state, city/suburb/town, out-of-state tuition, student-faculty ratio, etc.) of the universities which located in the state that the mouse hovers on top. If the mouse is not on the map, then the table displays all universities in our dataset, ordered by descending order of world rank.

#### Second level:
Input will be “select box” of the world ranking of the universities (i.e., 1-20, 20-50, 50-100, 101-50, etc.); output will have two parts. The first part is a bar plot (function: plotOutput) of the number of international students at the universities which meet the ranking condition, colored by selectivity. The second part is an updated (filtered) table of first level.

#### Third level:
The third level of interactive will be related to modeling. Input will be one of the predictor variables. Output will be the R output and a dot plot (if selecting categorical variable such as selectivity, campus size, world rank) or a line plot (if showing continuous variables such as tuition fee or student-teacher ratio) showing the relationship between the selected predictor and the international student population within our dataset. We can also let the user select one continuous plus one categorical variable so that we can incorporate the "group_by" function or interaction in plotting/modeling.

 

