

```{r init}
library(tidyverse)

```


```{r Import Data}
#Import Data
data <- read.csv(file = 'dataset/full_data_leftjoinCarnegie.csv')
```


```{r Plot: National College Rankings and International Student Population}
ggplot(data, aes(x = national_rank_kaggle, y= (international_students_opendoors)), na.rm=T) + xlab("Ranking (ARWU)") + ylab("International Student Population (Opendoors)")+ geom_point() + geom_smooth() + xlim(0, 115)
#This demonstrates Positive correlation between National ranking and international student population: higher ranking (lower number) and higher international student population.
```
```{r Plot: World College Rankings and International Student Population}
ggplot(data, aes(x = world_rank_arwu, y= log(international_students_opendoors)), na.rm=T)+ xlab("Ranking (Kaggle)") + ylab("Log International Student Population (Opendoors)")+ geom_point() + geom_smooth() + xlim(0, 210)
#This demonstrates Positive correlation between World ranking and international student population: higher ranking (lower number) and higher international student population.
```


```{r Plot: National College Rankings and Tuition}
ggplot(data, aes(x = national_rank_kaggle, y= (tuition_kaggle)), na.rm=T) + xlab("Ranking (Kaggle)") + ylab("Tuition (Kaggle)")+ geom_point() + geom_smooth() + xlim(0, 115)
#Positive correlation between ranking and Tuition: higher ranking (lower number) and higher Tuition

```


```{r Plot: College Rankings and Overall Student Population}
ggplot(data, aes(x = national_rank_kaggle, y= (enrollment_kaggle)), na.rm=T) + xlab("Ranking (Kaggle)") + ylab("Student Enrollment (Kaggle)")+ geom_point() + geom_smooth() + xlim(0, 115)
ggplot(data, aes(x = national_rank_kaggle, y= (enrollment_top120enrollment)), na.rm=T) + xlab("Ranking (Kaggle)") + ylab("Student Enrollment (Top 120 Enrollment)")+ geom_point() + geom_smooth() + xlim(0, 120)
#Positive correlation between ranking and student population:: higher ranking (lower number) and higher student population
```



```{r Summary}
#Summary 
data_sum <- data %>% filter(!is.na(national_rank_arwu))%>% summarize(university, national_rank_arwu, world_rank_arwu, ) %>% arrange(world_rank_arwu)

data_sum_groupstate <- data %>% filter(!is.na(national_rank_arwu))%>% group_by(state)%>% summarize(university, national_rank_arwu, world_rank_arwu, ) %>% arrange(world_rank_arwu)
#Positive correlation between ranking and student population:: higher ranking (lower number) and higher student population
```


