--- 
title: Dataset Proposal 
author: All team members 
date: '2022-10-14' 
slug: [] 
categories: [] 
tags: [] 
description: "Blog post 1: We propose three datasets on US colleges and international student population" 
toc: yes 
authors: [] 
series: [] 
lastmod: '2022-10-03T07:38:30-04:00'
featuredVideo: ~ 
featuredImage: ~ 
---


## Dataset 1 – US Colleges with leading number of international students ([link to the original data source](https://opendoorsdata.org/data/international-students/leading-institutions-by-institutional-type/))

This dataset is from Opendoors, which describes US higher-education institutions with the top 40 leading international student population during the 2003-2021 academic years for five distinct institutional types (doctoral-granting universities, master’s colleges and universities, baccalaureate colleges, associate’s colleges, and special focus institutions.) We downloaded the raw dataset in xlsx format and chose the 2020-2021 academic year. We also did some basic processing and converted it to a csv file. We were able to load and clean data. The processed dataset has 200 rows and 4 columns, with each row representing one institution and columns representing its name, city, state, and the number of enrolling international students, sorted by descending order of international students.

<br>

We will be able to explore how the international student population is related to the university ranking and geographic location among these “top-picked” US universities. This dataset size is limited. We will need to find other datasets that contain information specific to those 200 colleges and locations. We will address this by the small dataset size, by merging other datasets or webscraping. Consider this post’s future work subsection.




## Dataset 2 - Rankings of the best American undergraduate programs ([link to the original data source](https://www.kaggle.com/datasets/neelgajare/2022-usa-college-rankings-more))
   
This dataset is from Kaggle, which describes rankings of the best universities for undergraduate programs in the US, containing information of 392 universities in 2022. The data was collected for Kaggle competition as a clustering problem by comparing tuition fees and enrollment numbers. We were able to download the dataset in csv format. Overall, this dataset has 392 rows and 4 columns, with each row representing one institution and columns representing the US News ranking based on their undergraduate program, name, out-of-state tuition, and the number of students attending undergraduate college.

<br>

For data cleaning, there are some universities which are missing data on tuition fees, so we need to remove or impute them when conducting analysis (generating plots, maps, running regression models). There is no information on the international student population, so we will need to find this data point from other sources. We are interested in adding a column of booleans to indicate whether the university is a public university or a private university. Within the current dataset, we are able to explore the relationship between the ranking of a university and its tuition fee. If we can merge the above-mentioned two columns (international population and private vs public), we will be able to further explore multiple factors that are correlated with international student enrollment. 


## Dataset 3 – US Universities with highest percentage of international student body ([link to the original data source](https://www.usnews.com/best-colleges/rankings/national-universities/most-international))


This dataset is from USNews that describes 231 US universities (national universities and liberal arts colleges) in 2022 with top proportions of international students, which was collected for publishing consumer advice, rankings, and relevant analysis. USNews is a very sourceful website commonly used by students for collecting and comparing universities’ information. We were able to do web scraping and generate the csv file for the dataset. Essentially, this data has 231 rows with 4 columns that represent the school name, location, and percentage of international students, and whether it is national university or liberal arts; it is sorted by descending percentage.

<br>

We are interested in adding a column that contains the total student population, which will help us compute the overall international student body population. We also are interested in finding their respective rankings. A main challenge is that while the schools may have high percentage of international students, they may not have a known ranking, which will be difficult to impute. We only scraped universities with at least 5% international student body, which limits the dataset size. Besides, the dataset we used is mainly the national universities international student percentage ranking. When we merged the national universities data and liberal arts universities data, there were outlier(s) such as 49% of the total student population. So, we might also consider either eliminating these data in case there are outliers data that influence the whole dataset or descaling the weight of the outliers (use Huber Regression). Hence, joining and handling outliers for future datasets might be a challenge for this dataset.


## Future Work

We plan to add more data with more features/factors that may influence international student 'permeation' and enrollment (i.e. Selectivity, Carnegie Classification, Public/Private, State political party affiliation, Global mobility data, Geographic regions, etc). In doing so, we hope we'll find interesting relationships between the above variables and international student population and college rankings.

<br>

We are also interested in other datasets and will look into [QS](https://www.topuniversities.com/university-rankings/world-university-rankings/2023) and [ARWU](https://www.shanghairanking.com/rankings/arwu/2022) ranking and many more to come.


